project_name: treegen

builds:
  - main: ./main.go
    binary: treegen
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: callmegautam 
    name: treegen

